spring:
  config:
    activate:
      on-profile: docker
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/db?useUnicode=true&charaterEncoding=utf-8
      username: root
      password: root123
      pool-name: hikari-cp
      maximum-pool-size: 5
      minimum-idle: 2
      max-lifetime: 30000
      validation-timeout: 10000
      connection-test-query: SELECT 1
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/db?useUnicode=true&charaterEncoding=utf-8
    user: ${spring.datasource.hikari.username}
    password: ${spring.datasource.hikari.password}



