spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway:
    enabled: false
    baseline-on-migrate: false

#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
#        SQL: DEBUG
---
spring:
  config:
    activate:
      on-profile: h2db
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      maximum-pool-size: 80
      validation-timeout: 10000
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
---
spring:
  config:
    activate:
      on-profile: dockerdb
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/db?useUnicode=true&charaterEncoding=utf-8
      username: root
      password: root123
      pool-name: hikari-cp
      maximum-pool-size: 5
      minimum-idle: 2
      max-lifetime: 30000
      validation-timeout: 10000
      connection-test-query: SELECT 1
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/db?useUnicode=true&charaterEncoding=utf-8
    user: ${spring.datasource.hikari.username}
    password: ${spring.datasource.hikari.password}

