spring:
  application:
    name: "spring-api"

logging:
  level:
    jdbc:
      sqltiming: 'off'
      audit: 'off'
      connection: 'off'
      resultset: 'off'
      resultsettable: 'off'
      sqlonly: info
    org.springframework:
      security: error
    com:
      betheproud: info