spring:
    redis:
        host: localhost
        port: 6379
        timeout: 3000
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1ms
                min-idle: 0

#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
#        SQL: DEBUG
---
spring:
    config:
        activate:
            on-profile: docker-redis

