server:
    port: 9090

spring:
    application:
        name: app-auth
    config:
        import: "classpath:application-rds.yml"
    profiles:
        group:
            h2: h2-db, docker-redis
            docker: docker-db, docker-redis
